-- Curated 2026/27 Premier League market bundle.
-- Safe to rerun: definitions are updated in place and group instances are untouched.

INSERT INTO market_catalog (
  id, slug, title, description, category, image_url, outcomes,
  initial_probabilities, closes_at, resolution_source, edge_cases,
  oracle_type, initial_liquidity, status, featured, created_by
)
VALUES
  ('pl-2026-27-winner', 'pl-2026-27-winner', 'Who will win the 2026/27 Premier League?', 'This market resolves to the club officially crowned Premier League champion for the 2026/27 season.', 'Premier League', '/league-logos/premier-league-dark.png', '["Arsenal", "Aston Villa", "AFC Bournemouth", "Brentford", "Brighton & Hove Albion", "Chelsea", "Coventry City", "Crystal Palace", "Everton", "Fulham", "Hull City", "Ipswich Town", "Leeds United", "Liverpool", "Manchester City", "Manchester United", "Newcastle United", "Nottingham Forest", "Tottenham Hotspur", "Sunderland"]'::jsonb, '{"Arsenal":0.14,"Aston Villa":0.05,"AFC Bournemouth":0.03,"Brentford":0.03,"Brighton & Hove Albion":0.035,"Chelsea":0.1,"Coventry City":0.005,"Crystal Palace":0.035,"Everton":0.025,"Fulham":0.02,"Hull City":0.005,"Ipswich Town":0.005,"Leeds United":0.015,"Liverpool":0.13,"Manchester City":0.16,"Manchester United":0.075,"Newcastle United":0.065,"Nottingham Forest":0.04,"Tottenham Hotspur":0.055,"Sunderland":0.01}'::jsonb, '2027-05-30T14:00:00+00:00'::timestamptz, 'https://www.premierleague.com/en/clubs', 'If the competition is abandoned, settlement waits for the league''s official ruling.', 'manual', 120000.0, 'open', true, 'probable'),
  ('pl-2026-27-golden-boot', 'premier-league-golden-boot-2026-27', 'Who will win the 2026/27 Premier League Golden Boot?', 'Resolves to the player officially awarded the 2026/27 Premier League Golden Boot.', 'Premier League', '/league-logos/premier-league-dark.png', '["Erling Haaland", "Igor Thiago", "Antoine Semenyo", "Hugo Ekitike", "Mohamed Salah", "Joao Pedro", "Viktor Gyokeres", "Alexander Isak", "Bryan Mbeumo", "Ollie Watkins", "Bukayo Saka", "Any other player", "Shared award"]'::jsonb, '{"Erling Haaland":0.22,"Igor Thiago":0.1,"Antoine Semenyo":0.08,"Hugo Ekitike":0.08,"Mohamed Salah":0.08,"Joao Pedro":0.07,"Viktor Gyokeres":0.07,"Alexander Isak":0.06,"Bryan Mbeumo":0.05,"Ollie Watkins":0.05,"Bukayo Saka":0.04,"Any other player":0.08,"Shared award":0.02}'::jsonb, '2027-05-30T14:00:00+00:00'::timestamptz, 'Official Premier League Golden Boot announcement and final player statistics', 'Any unlisted sole winner resolves to Any other player. If the award is shared by multiple players, Shared award wins.', 'manual', 90000.0, 'open', true, 'probable'),
  ('pl-2026-27-most-assists', 'premier-league-most-assists-2026-27', 'Who will record the most Premier League assists in 2026/27?', 'Resolves to the player officially credited with the most assists in the 2026/27 Premier League season.', 'Premier League', '/league-logos/premier-league-dark.png', '["Bruno Fernandes", "Mohamed Salah", "Bukayo Saka", "Cole Palmer", "Phil Foden", "Declan Rice", "Morgan Gibbs-White", "Florian Wirtz", "Antoine Semenyo", "Eberechi Eze", "Any other player", "Shared lead"]'::jsonb, '{"Bruno Fernandes":0.16,"Mohamed Salah":0.1,"Bukayo Saka":0.1,"Cole Palmer":0.1,"Phil Foden":0.08,"Declan Rice":0.07,"Morgan Gibbs-White":0.06,"Florian Wirtz":0.08,"Antoine Semenyo":0.05,"Eberechi Eze":0.05,"Any other player":0.12,"Shared lead":0.03}'::jsonb, '2027-05-30T14:00:00+00:00'::timestamptz, 'Official Premier League Playmaker Award announcement and final player statistics', 'Any unlisted sole leader resolves to Any other player. If multiple players share the official lead, Shared lead wins.', 'manual', 90000.0, 'open', true, 'probable'),
  ('pl-2026-27-golden-glove', 'premier-league-golden-glove-2026-27', 'Who will win the 2026/27 Premier League Golden Glove?', 'Resolves to the goalkeeper officially awarded the 2026/27 Premier League Golden Glove.', 'Premier League', '/league-logos/premier-league-dark.png', '["David Raya", "Gianluigi Donnarumma", "Alisson Becker", "Robert Sanchez", "Nick Pope", "Emiliano Martinez", "Jordan Pickford", "Dean Henderson", "Bart Verbruggen", "Guglielmo Vicario", "Any other goalkeeper", "Shared award"]'::jsonb, '{"David Raya":0.16,"Gianluigi Donnarumma":0.15,"Alisson Becker":0.12,"Robert Sanchez":0.09,"Nick Pope":0.08,"Emiliano Martinez":0.07,"Jordan Pickford":0.06,"Dean Henderson":0.07,"Bart Verbruggen":0.05,"Guglielmo Vicario":0.05,"Any other goalkeeper":0.08,"Shared award":0.02}'::jsonb, '2027-05-30T14:00:00+00:00'::timestamptz, 'Official Premier League Golden Glove announcement and final goalkeeper statistics', 'Any unlisted sole winner resolves to Any other goalkeeper. If the award is shared, Shared award wins.', 'manual', 85000.0, 'open', false, 'probable'),
  ('pl-2026-27-highest-promoted-club', 'highest-promoted-premier-league-club-2026-27', 'Which promoted club will finish highest in the Premier League?', 'Resolves to the highest-placed promoted club in the final 2026/27 Premier League table.', 'Premier League', '/league-logos/premier-league-dark.png', '["Coventry City", "Ipswich Town", "Hull City"]'::jsonb, '{"Coventry City":0.34,"Ipswich Town":0.38,"Hull City":0.28}'::jsonb, '2027-05-30T14:00:00+00:00'::timestamptz, 'Official final Premier League table', 'The official final table and its tie-break rules determine the highest-placed club. Points deductions count.', 'manual', 50000.0, 'open', false, 'probable'),
  ('pl-2026-27-any-promoted-survives', 'any-promoted-club-survives-2026-27', 'Will any promoted club survive the 2026/27 Premier League season?', 'Resolves Yes if Coventry City, Ipswich Town, or Hull City finish 17th or higher in the final table.', 'Premier League', '/league-logos/premier-league-dark.png', '["Yes", "No"]'::jsonb, NULL, '2027-05-30T14:00:00+00:00'::timestamptz, 'Official final Premier League table', 'Points deductions count. Yes wins if at least one promoted club is outside the relegation places in the official final table.', 'manual', 35000.0, 'open', false, 'probable'),
  ('pl-2026-27-champion-over-89-5', 'premier-league-champion-over-89-5-points-2026-27', 'Will the Premier League champion finish with over 89.5 points?', 'Resolves Over 89.5 if the 2026/27 champion records at least 90 points; otherwise Under 89.5.', 'Premier League', '/league-logos/premier-league-dark.png', '["Over 89.5", "Under 89.5"]'::jsonb, NULL, '2027-05-30T14:00:00+00:00'::timestamptz, 'Official final Premier League table', 'Use the champion''s points after every official deduction or adjustment reflected in the final table.', 'manual', 35000.0, 'open', false, 'probable'),
  ('pl-2026-27-arsenal-top-five', 'arsenal-top-five-2026-27', 'Will Arsenal finish in the Premier League top five?', 'Resolves Yes if Arsenal finish fifth or higher in the final 2026/27 Premier League table.', 'Premier League', '/league-logos/premier-league-dark.png', '["Yes", "No"]'::jsonb, NULL, '2027-05-30T14:00:00+00:00'::timestamptz, 'Official final Premier League table', 'Points deductions count if reflected in the official final table.', 'manual', 35000.0, 'open', false, 'probable'),
  ('pl-2026-27-man-utd-top-five', 'manchester-united-top-five-2026-27', 'Will Manchester United finish in the Premier League top five?', 'Resolves Yes if Manchester United finish fifth or higher in the final 2026/27 Premier League table.', 'Premier League', '/league-logos/premier-league-dark.png', '["Yes", "No"]'::jsonb, NULL, '2027-05-30T14:00:00+00:00'::timestamptz, 'Official final Premier League table', 'Points deductions count if reflected in the official final table.', 'manual', 35000.0, 'open', false, 'probable'),
  ('pl-2026-27-chelsea-vs-spurs', 'chelsea-vs-tottenham-higher-finish-2026-27', 'Who will finish higher: Chelsea or Tottenham Hotspur?', 'Resolves to the club placed higher in the final 2026/27 Premier League table.', 'Premier League', '/league-logos/premier-league-dark.png', '["Chelsea", "Tottenham Hotspur"]'::jsonb, NULL, '2027-05-30T14:00:00+00:00'::timestamptz, 'Official final Premier League table', 'Official league tie-break rules determine which club finishes higher. Points deductions count.', 'manual', 40000.0, 'open', false, 'probable'),
  ('pl-2026-27-first-manager-to-leave', 'first-premier-league-manager-to-leave-2026-27', 'Who will be the first Premier League manager to leave?', 'Resolves to the first permanent Premier League manager to stop holding their role during the 2026/27 season.', 'Premier League', '/league-logos/premier-league-dark.png', '["Mikel Arteta — Arsenal", "Unai Emery — Aston Villa", "Marco Rose — AFC Bournemouth", "Keith Andrews — Brentford", "Fabian Hurzeler — Brighton", "Xabi Alonso — Chelsea", "Frank Lampard — Coventry City", "Pierre Sage — Crystal Palace", "David Moyes — Everton", "Alvaro Arbeloa — Fulham", "Sergej Jakirovic — Hull City", "Gary O''Neil — Ipswich Town", "Daniel Farke — Leeds United", "Andoni Iraola — Liverpool", "Enzo Maresca — Manchester City", "Michael Carrick — Manchester United", "Eddie Howe — Newcastle United", "Oliver Glasner — Nottingham Forest", "Regis Le Bris — Sunderland", "Roberto De Zerbi — Tottenham Hotspur", "No manager leaves", "Joint / indistinguishable timing"]'::jsonb, NULL, '2026-08-21T18:45:00+00:00'::timestamptz, 'Official club announcement, supported by the Premier League manager directory', 'Dismissal, resignation, or mutual consent counts when officially announced. Temporary absence does not. If two departures are announced at the same recorded time, Joint / indistinguishable timing wins. No manager leaves wins only if every listed manager remains through the final matchday.', 'manual', 120000.0, 'open', true, 'probable'),
  ('pl-2026-27-highest-scoring-club', 'highest-scoring-premier-league-club-2026-27', 'Which club will score the most Premier League goals in 2026/27?', 'Resolves to the club with the most goals scored in the final 2026/27 Premier League table.', 'Premier League', '/league-logos/premier-league-dark.png', '["Arsenal", "Aston Villa", "AFC Bournemouth", "Brentford", "Brighton & Hove Albion", "Chelsea", "Coventry City", "Crystal Palace", "Everton", "Fulham", "Hull City", "Ipswich Town", "Leeds United", "Liverpool", "Manchester City", "Manchester United", "Newcastle United", "Nottingham Forest", "Tottenham Hotspur", "Sunderland", "Tie"]'::jsonb, '{"Arsenal":0.14,"Aston Villa":0.05,"AFC Bournemouth":0.03,"Brentford":0.03,"Brighton & Hove Albion":0.035,"Chelsea":0.1,"Coventry City":0.005,"Crystal Palace":0.035,"Everton":0.025,"Fulham":0.02,"Hull City":0.005,"Ipswich Town":0.005,"Leeds United":0.015,"Liverpool":0.13,"Manchester City":0.16,"Manchester United":0.075,"Newcastle United":0.065,"Nottingham Forest":0.04,"Tottenham Hotspur":0.055,"Sunderland":0.01,"Tie":0.02}'::jsonb, '2027-05-30T14:00:00+00:00'::timestamptz, 'Official final Premier League table', 'If two or more clubs finish level for most goals scored, Tie wins. Points deductions do not alter goals scored.', 'manual', 120000.0, 'open', false, 'probable')
ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug,
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  image_url = EXCLUDED.image_url,
  outcomes = EXCLUDED.outcomes,
  initial_probabilities = EXCLUDED.initial_probabilities,
  closes_at = EXCLUDED.closes_at,
  resolution_source = EXCLUDED.resolution_source,
  edge_cases = EXCLUDED.edge_cases,
  oracle_type = EXCLUDED.oracle_type,
  initial_liquidity = EXCLUDED.initial_liquidity,
  status = EXCLUDED.status,
  featured = EXCLUDED.featured,
  created_by = EXCLUDED.created_by,
  updated_at = now();

-- Retire superseded catalogue definitions without deleting any imported event.
UPDATE market_catalog
SET status = 'closed', updated_at = now()
WHERE id IN (
  'pl-2026-27-arsenal-top-four',
  'pl-2026-27-united-above-liverpool'
);
