-- Concrete league questions attached automatically with each table challenge.
-- Safe to rerun; imported group markets retain independent prices and trades.

INSERT INTO market_catalog (
  id, slug, title, description, category, image_url, outcomes,
  initial_probabilities, closes_at, resolution_source, edge_cases,
  oracle_type, initial_liquidity, status, featured, created_by
)
VALUES
  ('pl-2026-27-last-place', 'pl-2026-27-last-place', 'Which club will finish last in the 2026/27 Premier League?', 'This market resolves to the club in last place in the official final 2026/27 Premier League table.', 'Premier League', '/league-logos/premier-league-dark.png', '["Arsenal","Aston Villa","AFC Bournemouth","Brentford","Brighton & Hove Albion","Chelsea","Coventry City","Crystal Palace","Everton","Fulham","Hull City","Ipswich Town","Leeds United","Liverpool","Manchester City","Manchester United","Newcastle United","Nottingham Forest","Tottenham Hotspur","Sunderland"]'::jsonb, NULL, '2027-05-30T14:00:00+00:00'::timestamptz, 'https://www.premierleague.com/en/clubs', 'Use the official final table after every points deduction and league ruling. Official tie-break rules determine last place.', 'manual', 90000, 'open', false, 'probable'),
  ('laliga-2026-27-winner', 'laliga-2026-27-winner', 'Who will win the 2026/27 La Liga?', 'This market resolves to the club officially crowned La Liga champion for the 2026/27 season.', 'La Liga', '/league-logos/la-liga.png', '["Athletic Club","Atlético de Madrid","CA Osasuna","Celta","Deportivo Alavés","Elche CF","FC Barcelona","Getafe CF","Levante UD","Málaga CF","Racing Santander","Rayo Vallecano","RC Deportivo","RCD Espanyol","Real Betis","Real Madrid","Real Sociedad","Sevilla FC","Valencia CF","Villarreal CF"]'::jsonb, NULL, '2027-06-01T00:00:00+00:00'::timestamptz, 'https://www.laliga.com/en-US/laliga-easports/clubs', 'If the competition is abandoned, settlement waits for the league''s official ruling.', 'manual', 120000, 'open', false, 'probable'),
  ('laliga-2026-27-last-place', 'laliga-2026-27-last-place', 'Which club will finish last in the 2026/27 La Liga?', 'This market resolves to the club in last place in the official final 2026/27 La Liga table.', 'La Liga', '/league-logos/la-liga.png', '["Athletic Club","Atlético de Madrid","CA Osasuna","Celta","Deportivo Alavés","Elche CF","FC Barcelona","Getafe CF","Levante UD","Málaga CF","Racing Santander","Rayo Vallecano","RC Deportivo","RCD Espanyol","Real Betis","Real Madrid","Real Sociedad","Sevilla FC","Valencia CF","Villarreal CF"]'::jsonb, NULL, '2027-06-01T00:00:00+00:00'::timestamptz, 'https://www.laliga.com/en-US/laliga-easports/clubs', 'Use the official final table after every points deduction and league ruling. Official tie-break rules determine last place.', 'manual', 90000, 'open', false, 'probable'),
  ('serie-a-2026-27-winner', 'serie-a-2026-27-winner', 'Who will win the 2026/27 Serie A?', 'This market resolves to the club officially crowned Serie A champion for the 2026/27 season.', 'Serie A', '/league-logos/serie-a-dark.png', '["Atalanta","Bologna","Cagliari","Como","Fiorentina","Frosinone","Genoa","Inter","Juventus","Lazio","Lecce","AC Milan","Monza","Napoli","Parma","Roma","Sassuolo","Torino","Udinese","Venezia"]'::jsonb, NULL, '2027-06-01T00:00:00+00:00'::timestamptz, 'https://www.legaseriea.it/team', 'If the competition is abandoned, settlement waits for the league''s official ruling.', 'manual', 120000, 'open', false, 'probable'),
  ('serie-a-2026-27-last-place', 'serie-a-2026-27-last-place', 'Which club will finish last in the 2026/27 Serie A?', 'This market resolves to the club in last place in the official final 2026/27 Serie A table.', 'Serie A', '/league-logos/serie-a-dark.png', '["Atalanta","Bologna","Cagliari","Como","Fiorentina","Frosinone","Genoa","Inter","Juventus","Lazio","Lecce","AC Milan","Monza","Napoli","Parma","Roma","Sassuolo","Torino","Udinese","Venezia"]'::jsonb, NULL, '2027-06-01T00:00:00+00:00'::timestamptz, 'https://www.legaseriea.it/team', 'Use the official final table after every points deduction and league ruling. Official tie-break rules determine last place.', 'manual', 90000, 'open', false, 'probable'),
  ('bundesliga-2026-27-winner', 'bundesliga-2026-27-winner', 'Who will win the 2026/27 Bundesliga?', 'This market resolves to the club officially crowned Bundesliga champion for the 2026/27 season.', 'Bundesliga', '/league-logos/bundesliga-dark.png', '["Bayern Munich","Borussia Dortmund","RB Leipzig","VfB Stuttgart","TSG Hoffenheim","Bayer Leverkusen","SC Freiburg","Eintracht Frankfurt","FC Augsburg","Mainz 05","Union Berlin","Borussia Mönchengladbach","Hamburger SV","1. FC Köln","Werder Bremen","Schalke 04","SV Elversberg","SC Paderborn"]'::jsonb, NULL, '2027-06-01T00:00:00+00:00'::timestamptz, 'https://www.bundesliga.com/en/bundesliga/clubs', 'If the competition is abandoned, settlement waits for the league''s official ruling.', 'manual', 120000, 'open', false, 'probable'),
  ('bundesliga-2026-27-last-place', 'bundesliga-2026-27-last-place', 'Which club will finish last in the 2026/27 Bundesliga?', 'This market resolves to the club in last place in the official final 2026/27 Bundesliga table.', 'Bundesliga', '/league-logos/bundesliga-dark.png', '["Bayern Munich","Borussia Dortmund","RB Leipzig","VfB Stuttgart","TSG Hoffenheim","Bayer Leverkusen","SC Freiburg","Eintracht Frankfurt","FC Augsburg","Mainz 05","Union Berlin","Borussia Mönchengladbach","Hamburger SV","1. FC Köln","Werder Bremen","Schalke 04","SV Elversberg","SC Paderborn"]'::jsonb, NULL, '2027-06-01T00:00:00+00:00'::timestamptz, 'https://www.bundesliga.com/en/bundesliga/clubs', 'Use the official final table after every points deduction and league ruling. Official tie-break rules determine last place.', 'manual', 90000, 'open', false, 'probable'),
  ('ligue-1-2026-27-winner', 'ligue-1-2026-27-winner', 'Who will win the 2026/27 Ligue 1?', 'This market resolves to the club officially crowned Ligue 1 champion for the 2026/27 season.', 'Ligue 1', '/league-logos/ligue-1.png', '["Angers SCO","AJ Auxerre","Stade Brestois 29","Le Havre AC","RC Lens","LOSC Lille","FC Lorient","Olympique Lyonnais","Le Mans FC","Olympique de Marseille","AS Monaco","OGC Nice","Paris Saint-Germain","Stade Rennais","RC Strasbourg","Toulouse FC","ESTAC Troyes","Paris FC"]'::jsonb, NULL, '2027-06-01T00:00:00+00:00'::timestamptz, 'https://ligue1.com/en/articles/l1_article_5292-the-2026-27-ligue-1-mc-donald-s-calendar-is-released', 'If the competition is abandoned, settlement waits for the league''s official ruling.', 'manual', 120000, 'open', false, 'probable'),
  ('ligue-1-2026-27-last-place', 'ligue-1-2026-27-last-place', 'Which club will finish last in the 2026/27 Ligue 1?', 'This market resolves to the club in last place in the official final 2026/27 Ligue 1 table.', 'Ligue 1', '/league-logos/ligue-1.png', '["Angers SCO","AJ Auxerre","Stade Brestois 29","Le Havre AC","RC Lens","LOSC Lille","FC Lorient","Olympique Lyonnais","Le Mans FC","Olympique de Marseille","AS Monaco","OGC Nice","Paris Saint-Germain","Stade Rennais","RC Strasbourg","Toulouse FC","ESTAC Troyes","Paris FC"]'::jsonb, NULL, '2027-06-01T00:00:00+00:00'::timestamptz, 'https://ligue1.com/en/articles/l1_article_5292-the-2026-27-ligue-1-mc-donald-s-calendar-is-released', 'Use the official final table after every points deduction and league ruling. Official tie-break rules determine last place.', 'manual', 90000, 'open', false, 'probable')
ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug,
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  image_url = EXCLUDED.image_url,
  outcomes = EXCLUDED.outcomes,
  initial_probabilities = EXCLUDED.initial_probabilities,
  closes_at = EXCLUDED.closes_at,
  resolution_source = EXCLUDED.resolution_source,
  edge_cases = EXCLUDED.edge_cases,
  oracle_type = EXCLUDED.oracle_type,
  initial_liquidity = EXCLUDED.initial_liquidity,
  status = EXCLUDED.status,
  featured = EXCLUDED.featured,
  created_by = EXCLUDED.created_by,
  updated_at = now();
