export const BRACKET_CHALLENGE = {
  id: "wc26-bracket-r32",
  prize: "up to $500",
  title: "World Cup Bracket Challenge",
  subtitle: "Free to enter. Submit the cleanest knockout bracket from the Round of 32 onward.",
  matchups: [
    { id: "m73", matchNo: 73, teams: ["South Africa", "Canada"], winner: "Canada", completed: true },
    { id: "m74", matchNo: 74, teams: ["Germany", "Paraguay"], winner: "Paraguay", completed: true },
    { id: "m75", matchNo: 75, teams: ["Netherlands", "Morocco"], winner: "Morocco", completed: true },
    { id: "m76", matchNo: 76, teams: ["Brazil", "Japan"], winner: "Brazil", completed: true },
    { id: "m77", matchNo: 77, teams: ["France", "Sweden"], winner: "France", completed: true },
    { id: "m78", matchNo: 78, teams: ["Ivory Coast", "Norway"], winner: "Norway", completed: true },
    { id: "m79", matchNo: 79, teams: ["Mexico", "Ecuador"], winner: "Mexico", completed: true },
    { id: "m80", matchNo: 80, teams: ["England", "DR Congo"], winner: "England", completed: true },
    { id: "m81", matchNo: 81, teams: ["USA", "Bosnia and Herzegovina"], winner: "USA", completed: true },
    { id: "m82", matchNo: 82, teams: ["Belgium", "Senegal"], winner: "Belgium", completed: true },
    { id: "m83", matchNo: 83, teams: ["Portugal", "Croatia"], winner: "Portugal", completed: true },
    { id: "m84", matchNo: 84, teams: ["Spain", "Austria"], winner: "Spain", completed: true },
    { id: "m85", matchNo: 85, teams: ["Switzerland", "Algeria"], winner: "Switzerland", completed: true },
    { id: "m86", matchNo: 86, teams: ["Argentina", "Cabo Verde"], winner: "Argentina", completed: true },
    { id: "m87", matchNo: 87, teams: ["Colombia", "Ghana"], winner: "Colombia", completed: true },
    { id: "m88", matchNo: 88, teams: ["Australia", "Egypt"], winner: "Egypt", completed: true },
  ],
};

const BRACKET_DERIVED_RESULTS = {
  m89: "France",
  m90: "Morocco",
  m91: "Norway",
  m92: "England",
  m93: "Belgium",
  m94: "Spain",
  m95: "Argentina",
  m96: "Switzerland",
  m97: "France",
  m98: "Spain",
  m99: "England",
  m100: "Argentina",
  m101: "Spain",
  m102: "Argentina",
  final: "Spain",
};

export const BRACKET_LOCKED_WINNERS = {
  ...Object.fromEntries(
    BRACKET_CHALLENGE.matchups
      .filter(matchup => matchup.completed && matchup.winner)
      .map(matchup => [matchup.id, matchup.winner]),
  ),
  ...BRACKET_DERIVED_RESULTS,
};

export const BRACKET_TEAM_CHANCES = {
  France: 23,
  Spain: 11,
  Argentina: 10,
  Brazil: 9,
  England: 8,
  Portugal: 6,
  Netherlands: 5,
  Germany: 4,
  Colombia: 4,
  Belgium: 3,
  USA: 3,
  Mexico: 3,
  Canada: 2,
  Switzerland: 2,
  Croatia: 1,
  Morocco: 1,
  Senegal: 1,
  Japan: 1,
  Norway: 1,
  Austria: 1,
  Ecuador: 1,
  Ghana: 1,
  Sweden: 1,
  "Ivory Coast": 1,
  Australia: 1,
  Egypt: 1,
  Algeria: 1,
  Paraguay: 1,
  "DR Congo": 1,
  "Bosnia and Herzegovina": 1,
  "Cabo Verde": 1,
  "South Africa": 0.5,
};
